#!/bin/sh -x

[ $# -ne 1 ] && { echo "give serial# as sole parameter"; exit 1; }

VERSION=2.0
SERIAL="$1"

cp210x-program	\
		--set-product-string=UART384-$VERSION \
		--set-version=$VERSION \
		--set-serial-number="$SERIAL" \
		--set-bus-powered=true \
		--write-cp210x
